/*
 * This file was generated by the program errorParser
 * using the input file ../tests/xml/no_groupident.xml.
 * Date: Tue Dec 30 10:04:13 2008.
 *
 * The version of the XML error file is 0.1.
 *
 * Copyright (C) 2008 D. Prevost
 *
 * This file is both a test and an example.
 *
 * This file may be distributed and/or modified under the terms of the 
 * MIT License as described by the Open Source Initiative 
 * (http://opensource.org/licenses/mit-license.php) and appearing in 
 * the file COPYING included in the packaging of this software.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY, to the extent permitted by law; without even 
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
 * PURPOSE.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#ifndef GETERROR_H
#define GETERROR_H

#ifdef __cplusplus
extern "C" {
#endif

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#if defined(WIN32)
#  if defined(BULDING_ERROR_MESSAGE)
#    define ERROR_MESSAGE_EXPORT __declspec ( dllexport )
#  else
#    define ERROR_MESSAGE_EXPORT __declspec ( dllimport )
#  endif
#else
#  define ERROR_MESSAGE_EXPORT
#endif

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

/*
 * Use this function to access the error messages (defined in the xml
 * input file).
 * 
 * Parameters:
 *   - errnum    The error number
 *
 * Return values:
 *   - the error message if errnum is valid (exists)
 *   - NULL otherwise
 */
ERROR_MESSAGE_EXPORT
const char * prog_ErrorMessage( int errnum );

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#ifdef __cplusplus
}
#endif

#endif /* GETERROR_H */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

