/*
 * This file was generated by the program errorParser
 * using the input file ../tests/xml/one_error.xml.
 * Date: Mon May  5 09:47:53 2008.
 *
 * The version of this interface is 0.1.
 *
 * Copyright (C) 2008 D. Prevost
 *
 * This file is both a test and an example.
 *
 * This file may be distributed and/or modified under the terms of the
 * MIT License as described by the Open Source Initiative
 * (http://opensource.org/licenses/mit-license.php) and appearing in
 * the file COPYING included in the packaging of this software.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, to the extent permitted by law; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#include <stdlib.h> /* Any system file will do. Needed for NULL. */
#define BULDING_ERROR_MESSAGE
#include "getError.h"

struct prog_MsgStruct
{
    int  errorNumber;
    const char * message;
};

typedef struct prog_MsgStruct prog_MsgStruct;

/* MY_PROG_OK */
prog_MsgStruct prog_Msg0 = {
    0, "No error" };

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

/* Array of pointers to previous structs */
prog_MsgStruct * prog_MsgArray[1] = {
    &prog_Msg0
};

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

const char * prog_ErrorMessage( int errnum )
{
    int i;

    for ( i = 0; i < 1; ++i ) {
        if ( errnum == prog_MsgArray[i]->errorNumber ) {
            return prog_MsgArray[i]->message;
        }
    }

    return NULL;
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

