/* -*- c++ -*- */
/* :mode=c++:  - For jedit, previous line for emacs */
/*
 * Copyright (C) 2008-2009 Daniel Prevost <dprevost@users.sourceforge.net>
 *
 * This file may be distributed and/or modified under the terms of the
 * MIT License as described by the Open Source Initiative
 * (http://opensource.org/licenses/mit-license.php) and appearing in
 * the file COPYING included in the packaging of this software.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

#ifndef CFAMILY_HANDLER_H
#define CFAMILY_HANDLER_H

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

#include "AbstractHandler.h"

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

/** 
 * This class is abstract. It extend the abstract class abstractHandler for
 * files witten in the C family of languages (C, C#, etc.).
 *
 * It adds two common functions for all these files, addTop and addCopyright.
 */ 
class CfamilyHandler: public AbstractHandler {
   
public:

   // Do-nothing destructor
   virtual ~CfamilyHandler() {}
   
   // Start a C comment which will include basic info. For example, that
   // the file was generated by Error Parser, a time stamp, etc. 
   virtual void addTop( std::string & xmlFilename,
                        const char  * timeBuf,
                        const char  * version );
   
   // Add copyright notice(s) to the C comment started by addTop(), if any.
   virtual void addCopyright( Copyright & copy ) throw( MissingException );

   // Terminates the C comment started by addTop().
   virtual void addEndTop();
   
protected:
   
   CfamilyHandler();

};

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

#endif // CFAMILY_HANDLER_H

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--
