/*
 * Copyright (C) 2008 Daniel Prevost <dprevost@users.sourceforge.net>
 *
 * This file may be distributed and/or modified under the terms of the
 * MIT License as described by the Open Source Initiative
 * (http://opensource.org/licenses/mit-license.php) and appearing in
 * the file COPYING included in the packaging of this software.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

#include "CfamilyHandler.h"
#include "parser1.h"

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

using namespace std;

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

CfamilyHandler::CfamilyHandler()
{
   barrier = "/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */";
}

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

void CfamilyHandler::addTop( std::string & xmlFilename,
                             char        * timeBuf,
                             xmlChar     * version )
{
   out_stream << "/*" << endl;
   out_stream << " * This file was generated by the program errorParser" << endl;
   out_stream << " * using the input file " << xmlFilename << "." << endl;
   out_stream << " * Date: " << timeBuf << "." << endl;
   out_stream << " *" << endl;
   if ( version != NULL ) {
      out_stream << " * The version of this interface is " << version << "." << endl;
      out_stream << " *" << endl;
   }
}

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

void CfamilyHandler::addCopyright( xmlNode * node )
{
   string years, authors;
   string tmp, prefix = " * ";
   
   node = node->children;
   
   /* Go to the first element */
   while ( node->type != XML_ELEMENT_NODE ) { node = node->next; }
   stripText( node->children->content, years );
   
   /* Go to the next element */
   do { node = node->next; } while ( node->type != XML_ELEMENT_NODE );
   stripText( node->children->content, authors );
   
   out_stream << " * Copyright (C) " << years << " " << authors << endl;
   
   node = node->next;
   while ( node != NULL ) {
      if ( node->type == XML_ELEMENT_NODE ) {
         out_stream << " *" << endl;

         stripText( node->children->content, tmp );
         prettify( out_stream, tmp, prefix, ERRP_LINE_LENGTH );
      }
      node = node->next;
   }

   out_stream << " *" << endl;

}

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

void CfamilyHandler::addEndTop()
{
   out_stream << " */" << endl << endl;
   out_stream << barrier << endl << endl;
}

// --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--

