/*
 * This file was generated by the program errorParser
 * using the input file xml/no_copyright.xml.
 * Date: Mon Apr 21 17:04:00 2008.
 *
 * The version of this interface is 0.1.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#ifndef ERRORS_H
#define ERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

enum enumErrors
{
    /*
     * A dummy group identifier to test if this works.
     */

    /**
     * No error
     */
    MY_PROG_OK = 0,

    /**
     * Abnormal internal error - it should not happen!
     */
    MY_PROG_INTERNAL_ERROR = 1,

    /**
     * Cannot get a lock on a system object, the engine is "busy"
     *
     * This might be the result of either a very busy system where
     * unused cpu cycles are rare or a lock might be held by a crashed
     * process.
     */
    MY_PROG_ENGINE_BUSY = 2,

    /*
     * The following errors are network related.
     */

    /**
     * Generic socket error.
     */
    MY_PROG_SOCKET_ERROR = 25
};

typedef enum enumErrors enumErrors;

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#ifdef __cplusplus
}
#endif

#endif /* ERRORS_H */

