/*
 * This file was generated by the program errorParser
 * using the input file xml/no_copyright.xml.
 * Date: Mon Apr 21 17:04:00 2008.
 *
 * The version of this interface is 0.1.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#ifndef GETERROR_H
#define GETERROR_H

#ifdef __cplusplus
extern "C" {
#endif

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#if defined(WIN32)
#  if defined(BULDING_ERROR_MESSAGE)
#    define ERROR_MESSAGE_EXPORT __declspec ( dllexport )
#  else
#    define ERROR_MESSAGE_EXPORT __declspec ( dllimport )
#  endif
#else
#  define ERROR_MESSAGE_EXPORT
#endif

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

/*
 * Use this function to access the error messages (defined in the xml
 * input file).
 * 
 * Parameters:
 *   - errnum    The error number
 *
 * Return values:
 *   - the error message if errnum is valid (exists)
 *   - NULL otherwise
 */
ERROR_MESSAGE_EXPORT
const char * prog_ErrorMessage( int errnum );

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#ifdef __cplusplus
}
#endif

#endif /* GETERROR_H */

