/*
 * This file was generated by the program errorParser
 * using the input file xml/no_copyright.xml.
 * Date: Mon Apr 21 17:04:00 2008.
 *
 * The version of this interface is 0.1.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#include <stdlib.h> /* Any system file will do. Needed for NULL. */
#define BULDING_ERROR_MESSAGE
#include "getError.h"

struct prog_MsgStruct
{
    int  errorNumber;
    const char * message;
};

typedef struct prog_MsgStruct prog_MsgStruct;

/* MY_PROG_OK */
prog_MsgStruct prog_Msg0 = {
    0, "No error" };

/* MY_PROG_INTERNAL_ERROR */
prog_MsgStruct prog_Msg1 = {
    1, "Abnormal internal error - it should not happen!" };

/* MY_PROG_ENGINE_BUSY */
prog_MsgStruct prog_Msg2 = {
    2, "Cannot get a lock on a system object, the engine is \"busy\"" };

/* MY_PROG_SOCKET_ERROR */
prog_MsgStruct prog_Msg3 = {
    25, "Generic socket error." };

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

/* Array of pointers to previous structs */
prog_MsgStruct * prog_MsgArray[4] = {
    &prog_Msg0,
    &prog_Msg1,
    &prog_Msg2,
    &prog_Msg3
};

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

const char * prog_ErrorMessage( int errnum )
{
    int i;

    for ( i = 0; i < 4; ++i ) {
        if ( errnum == prog_MsgArray[i]->errorNumber ) {
            return prog_MsgArray[i]->message;
        }
    }

    return NULL;
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

