/*
 * This file was generated by the program errorParser
 * using the input file ../tests/xml/generic.xml.
 * Date: Wed Dec 31 17:37:26 2008.
 *
 * The version of the XML error file is 0.3.
 *
 * Copyright (C) 2006-2008 Daniel Prevost
 *
 * This file is part of Photon.
 *
 * This file may be distributed and/or modified under the terms of the 
 * GNU General Public License version 2 as published by the Free 
 * Software Foundation and appearing in the file COPYING included in 
 * the packaging of this library.
 *
 * This library is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#include <stdlib.h> /* Needed for NULL. */

#define BULDING_ERROR_MESSAGE
#include "errmsg.h"

struct testmsg_MsgStruct
{
    int  errorNumber;
    const char * message;
};

typedef struct testmsg_MsgStruct testmsg_MsgStruct;

/* MY_PROG_OK */
testmsg_MsgStruct testmsg_Msg0 = {
    0, "No error (adding a dummy this_is_a_percent_substitute to test this feature)" };

/* MY_PROG_INTERNAL_ERROR */
testmsg_MsgStruct testmsg_Msg1 = {
    666, "Abnormal internal error." };

/* MY_PROG_ENGINE_BUSY */
testmsg_MsgStruct testmsg_Msg2 = {
    1, "Cannot get a lock on a system object, the engine is \"busy\"." };

/* MY_PROG_NOT_ENOUGH_PSO_MEMORY */
testmsg_MsgStruct testmsg_Msg3 = {
    2, "Not enough memory in the PSO." };

/* MY_PROG_NOT_ENOUGH_HEAP_MEMORY */
testmsg_MsgStruct testmsg_Msg4 = {
    3, "Not enough heap memory (non-PSO memory)." };

/* MY_PROG_NOT_ENOUGH_RESOURCES */
testmsg_MsgStruct testmsg_Msg5 = {
    4, "There are not enough resources to correctly process the call." };

/* MY_PROG_WRONG_TYPE_HANDLE */
testmsg_MsgStruct testmsg_Msg6 = {
    5, "The provided handle is of the wrong type." };

/* MY_PROG_NULL_HANDLE */
testmsg_MsgStruct testmsg_Msg7 = {
    6, "The provided handle is NULL." };

/* MY_PROG_NULL_POINTER */
testmsg_MsgStruct testmsg_Msg8 = {
    7, "One of the arguments of an API function is an invalid NULL pointer." };

/* MY_PROG_INVALID_LENGTH */
testmsg_MsgStruct testmsg_Msg9 = {
    8, "An invalid length was provided." };

/* MY_PROG_PROCESS_ALREADY_INITIALIZED */
testmsg_MsgStruct testmsg_Msg10 = {
    21, "The process was already initialized." };

/* MY_PROG_PROCESS_NOT_INITIALIZED */
testmsg_MsgStruct testmsg_Msg11 = {
    22, "The process was not properly initialized." };

/* MY_PROG_INVALID_WATCHDOG_ADDRESS */
testmsg_MsgStruct testmsg_Msg12 = {
    23, "The watchdog address is invalid (empty string, NULL pointer, etc.)." };

/* MY_PROG_INCOMPATIBLE_VERSIONS */
testmsg_MsgStruct testmsg_Msg13 = {
    24, "API - memory-file version mismatch." };

/* MY_PROG_SOCKET_ERROR */
testmsg_MsgStruct testmsg_Msg14 = {
    25, "Generic socket error." };

/* MY_PROG_CONNECT_ERROR */
testmsg_MsgStruct testmsg_Msg15 = {
    26, "Socket error when trying to connect to the watchdog." };

/* MY_PROG_SEND_ERROR */
testmsg_MsgStruct testmsg_Msg16 = {
    27, "Socket error when trying to send a request to the watchdog." };

/* MY_PROG_RECEIVE_ERROR */
testmsg_MsgStruct testmsg_Msg17 = {
    28, "Socket error when trying to receive a reply from the watchdog." };

/* MY_PROG_BACKSTORE_FILE_MISSING */
testmsg_MsgStruct testmsg_Msg18 = {
    29, "The shared-memory backstore file is missing." };

/* MY_PROG_ERROR_OPENING_MEMORY */
testmsg_MsgStruct testmsg_Msg19 = {
    30, "Generic i/o error when attempting to open the shared memory." };

/* MY_PROG_LOGFILE_ERROR */
testmsg_MsgStruct testmsg_Msg20 = {
    41, "Error accessing the directory for the log files or error opening the log file itself." };

/* MY_PROG_SESSION_CANNOT_GET_LOCK */
testmsg_MsgStruct testmsg_Msg21 = {
    42, "Cannot get a lock on the session (a pthread_mutex or a critical section on Windows)." };

/* MY_PROG_SESSION_IS_TERMINATED */
testmsg_MsgStruct testmsg_Msg22 = {
    43, "An attempt was made to use a session object (a session handle) after this session was terminated." };

/* MY_PROG_INVALID_OBJECT_NAME */
testmsg_MsgStruct testmsg_Msg23 = {
    51, "Permitted characters for names are alphanumerics, spaces (\' \'), dashes (\'-\') and underlines (\'_\'). The first character must be alphanumeric." };

/* MY_PROG_NO_SUCH_OBJECT */
testmsg_MsgStruct testmsg_Msg24 = {
    52, "The object was not found (but its folder does exist)." };

/* MY_PROG_NO_SUCH_FOLDER */
testmsg_MsgStruct testmsg_Msg25 = {
    53, "One of the parent folder of an object does not exist." };

/* MY_PROG_OBJECT_ALREADY_PRESENT */
testmsg_MsgStruct testmsg_Msg26 = {
    54, "Attempt to create an object which already exists." };

/* MY_PROG_IS_EMPTY */
testmsg_MsgStruct testmsg_Msg27 = {
    55, "The object (data container) is empty." };

/* MY_PROG_WRONG_OBJECT_TYPE */
testmsg_MsgStruct testmsg_Msg28 = {
    56, "Attempt to create an object of an unknown object type or to open an object of the wrong type." };

/* MY_PROG_OBJECT_CANNOT_GET_LOCK */
testmsg_MsgStruct testmsg_Msg29 = {
    57, "Cannot get lock on the object. This might be the result of either a very busy system where unused cpu cycles are rare or a lock might be held by a crashed process." };

/* MY_PROG_REACHED_THE_END */
testmsg_MsgStruct testmsg_Msg30 = {
    58, "The search/iteration reached the end without finding a new item/record." };

/* MY_PROG_INVALID_ITERATOR */
testmsg_MsgStruct testmsg_Msg31 = {
    59, "An invalid value was used for a psoIteratorType parameter." };

/* MY_PROG_OBJECT_NAME_TOO_LONG */
testmsg_MsgStruct testmsg_Msg32 = {
    60, "The name of the object is too long. The maximum length of a name cannot be more than PSO_MAX_NAME_LENGTH (or PSO_MAX_FULL_NAME_LENGTH for the fully qualified name)." };

/* MY_PROG_FOLDER_IS_NOT_EMPTY */
testmsg_MsgStruct testmsg_Msg33 = {
    61, "You cannot delete a folder if there are still undeleted objects in it." };

/* MY_PROG_ITEM_ALREADY_PRESENT */
testmsg_MsgStruct testmsg_Msg34 = {
    62, "An item with the same key was found." };

/* MY_PROG_NO_SUCH_ITEM */
testmsg_MsgStruct testmsg_Msg35 = {
    63, "The item was not found in the hash map." };

/* MY_PROG_OBJECT_IS_DELETED */
testmsg_MsgStruct testmsg_Msg36 = {
    64, "The object is scheduled to be deleted soon. Operations on this data container are not permitted at this time." };

/* MY_PROG_OBJECT_NOT_INITIALIZED */
testmsg_MsgStruct testmsg_Msg37 = {
    65, "Object must be open first before you can access them." };

/* MY_PROG_ITEM_IS_IN_USE */
testmsg_MsgStruct testmsg_Msg38 = {
    66, "The data item is scheduled to be deleted soon or was just created and is not committed. Operations on this data item are not permitted at this time." };

/* MY_PROG_ITEM_IS_DELETED */
testmsg_MsgStruct testmsg_Msg39 = {
    67, "The data item is scheduled to be deleted soon. Operations on this data container are not permitted at this time." };

/* MY_PROG_OBJECT_IS_IN_USE */
testmsg_MsgStruct testmsg_Msg40 = {
    69, "The object is scheduled to be deleted soon or was just created and is not committed. Operations on this object are not permitted at this time." };

/* MY_PROG_OBJECT_IS_READ_ONLY */
testmsg_MsgStruct testmsg_Msg41 = {
    70, "The object is read-only and update operations on it are not permitted." };

/* MY_PROG_NOT_ALL_EDIT_ARE_CLOSED */
testmsg_MsgStruct testmsg_Msg42 = {
    71, "All edits must be closed before a commit." };

/* MY_PROG_A_SINGLE_UPDATER_IS_ALLOWED */
testmsg_MsgStruct testmsg_Msg43 = {
    72, "Read-only objects can only have one updater at a time." };

/* MY_PROG_INVALID_NUM_FIELDS */
testmsg_MsgStruct testmsg_Msg44 = {
    101, "The number of fields in the data definition is invalid." };

/* MY_PROG_INVALID_FIELD_TYPE */
testmsg_MsgStruct testmsg_Msg45 = {
    102, "The data type of the field definition is invalid." };

/* MY_PROG_INVALID_FIELD_LENGTH_INT */
testmsg_MsgStruct testmsg_Msg46 = {
    103, "The length of an integer field (PSO_INTEGER) is invalid." };

/* MY_PROG_INVALID_FIELD_LENGTH */
testmsg_MsgStruct testmsg_Msg47 = {
    104, "The length of a field (string or binary) is invalid." };

/* MY_PROG_INVALID_FIELD_NAME */
testmsg_MsgStruct testmsg_Msg48 = {
    105, "The name of the field contains invalid characters." };

/* MY_PROG_DUPLICATE_FIELD_NAME */
testmsg_MsgStruct testmsg_Msg49 = {
    106, "The name of the field is already used by another field in the current definition." };

/* MY_PROG_INVALID_PRECISION */
testmsg_MsgStruct testmsg_Msg50 = {
    107, "The precision of a PSO_DECIMAL field is invalid." };

/* MY_PROG_INVALID_SCALE */
testmsg_MsgStruct testmsg_Msg51 = {
    108, "The scale of a PSO_DECIMAL field is invalid." };

/* MY_PROG_INVALID_KEY_DEF */
testmsg_MsgStruct testmsg_Msg52 = {
    109, "The key definition is invalid or missing." };

/* MY_PROG_XML_READ_ERROR */
testmsg_MsgStruct testmsg_Msg53 = {
    201, "Error reading the XML buffer." };

/* MY_PROG_XML_INVALID_ROOT */
testmsg_MsgStruct testmsg_Msg54 = {
    202, "The root element is not the expected root." };

/* MY_PROG_XML_NO_SCHEMA_LOCATION */
testmsg_MsgStruct testmsg_Msg55 = {
    203, "The attribute xsi:schemaLocation was not found or is invalid." };

/* MY_PROG_XML_PARSER_CONTEXT_FAILED */
testmsg_MsgStruct testmsg_Msg56 = {
    204, "The creation of a new schema parser context failed." };

/* MY_PROG_XML_PARSE_SCHEMA_FAILED */
testmsg_MsgStruct testmsg_Msg57 = {
    205, "Failure when parsing the XML schema." };

/* MY_PROG_XML_VALID_CONTEXT_FAILED */
testmsg_MsgStruct testmsg_Msg58 = {
    206, "The creation of a new XML Schemas validation context failed." };

/* MY_PROG_XML_VALIDATION_FAILED */
testmsg_MsgStruct testmsg_Msg59 = {
    207, "Document validation for the xml buffer failed." };

/* MY_PROG_SEM_DESTROY_ERROR */
testmsg_MsgStruct testmsg_Msg60 = {
    601, "Abnormal internal error with sem_destroy." };

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

/* Array of pointers to previous structs */
testmsg_MsgStruct * testmsg_MsgArray[61] = {
    &testmsg_Msg0,
    &testmsg_Msg1,
    &testmsg_Msg2,
    &testmsg_Msg3,
    &testmsg_Msg4,
    &testmsg_Msg5,
    &testmsg_Msg6,
    &testmsg_Msg7,
    &testmsg_Msg8,
    &testmsg_Msg9,
    &testmsg_Msg10,
    &testmsg_Msg11,
    &testmsg_Msg12,
    &testmsg_Msg13,
    &testmsg_Msg14,
    &testmsg_Msg15,
    &testmsg_Msg16,
    &testmsg_Msg17,
    &testmsg_Msg18,
    &testmsg_Msg19,
    &testmsg_Msg20,
    &testmsg_Msg21,
    &testmsg_Msg22,
    &testmsg_Msg23,
    &testmsg_Msg24,
    &testmsg_Msg25,
    &testmsg_Msg26,
    &testmsg_Msg27,
    &testmsg_Msg28,
    &testmsg_Msg29,
    &testmsg_Msg30,
    &testmsg_Msg31,
    &testmsg_Msg32,
    &testmsg_Msg33,
    &testmsg_Msg34,
    &testmsg_Msg35,
    &testmsg_Msg36,
    &testmsg_Msg37,
    &testmsg_Msg38,
    &testmsg_Msg39,
    &testmsg_Msg40,
    &testmsg_Msg41,
    &testmsg_Msg42,
    &testmsg_Msg43,
    &testmsg_Msg44,
    &testmsg_Msg45,
    &testmsg_Msg46,
    &testmsg_Msg47,
    &testmsg_Msg48,
    &testmsg_Msg49,
    &testmsg_Msg50,
    &testmsg_Msg51,
    &testmsg_Msg52,
    &testmsg_Msg53,
    &testmsg_Msg54,
    &testmsg_Msg55,
    &testmsg_Msg56,
    &testmsg_Msg57,
    &testmsg_Msg58,
    &testmsg_Msg59,
    &testmsg_Msg60
};

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

const char * testmsg_ErrorMessage( int errnum )
{
    int i;

    for ( i = 0; i < 61; ++i ) {
        if ( errnum == testmsg_MsgArray[i]->errorNumber ) {
            return testmsg_MsgArray[i]->message;
        }
    }

    return NULL;
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

